### ISSUE TITLE
documents not processed, not supported mime type

### ISSUE THREAD

**Issue by ulrichhamann** [dveselov/docsbox#4]
I have found that tool, the api looks very simple , which I like.
Considering my current requirements it could be a good solution.

I cloned and installed from scratch and have run into known issue with rq.
After solving that by modifying the requirements.txt:
#git+https://github.com/nvie/rq.git#egg=rq
#rq
rq-scheduler==0.7.0

All services are up and running.
But unfortunately no document is successfully processed. Neither my own nor the sample inside that project:
Request:
curl -i  -F "file=@docsbox/docs/tests/samples/sample.docx"   http://localhost/api/v1/
Response:
HTTP/1.1 100 Continue

HTTP/1.1 400 BAD REQUEST
Server: nginx/1.4.6 (Ubuntu)
Date: Mon, 19 Feb 2018 16:06:21 GMT
Content-Type: application/json
Content-Length: 55
Connection: keep-alive

{"message": "Not supported mimetype: 'inode/x-empty'"}
 
Looking into container filesystem I use that files seem to be uploaded, but not transformed, and there is no id returned, what I expect.

Is it a known issue, do I something wrong?
Thanks and Kind Regards,
Uli

**Comment by dveselov** [comment]
Closed via #5
